// Dashboard
export const SET_FEATURED_PROPERTIES = "SET_FEATURED_PROPERTIES";
export const SET_RECENT_PROPERTIES = "SET_RECENT_PROPERTIES";
export const SET_HOMEPAGE_SECTION = "SET_HOMEPAGE_SECTION";
export const SET_THEME = "SET_THEME";
