/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://5wkaxv3rprhxbntygyqzer5i6i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lfapwzk6nvbclfhw2vetcr5eni",
    "aws_cognito_identity_pool_id": "us-east-1:59c7f5b8-4757-4fc6-8223-d9119a3e1e33",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BTLsL5hRc",
    "aws_user_pools_web_client_id": "4rc8vr82h5l73dn3f5avr4h0vc",
    "oauth": {
        "domain": "ey4tui3uo9b2-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/dashboard,https://main.d3pkie02zxxtk4.amplifyapp.com/dashboard",
        "redirectSignOut": "http://localhost:3000/signin,https://main.d3pkie02zxxtk4.amplifyapp.com/signin",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "AMAZON"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifydirect-storage-5389cf49203148-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
